name: geojson
description: Utilities to work with geojson data. Parser with a reactive api, search and geofencing
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/geojson
version: 0.7.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.6.0
  extra_pedantic: ^1.1.1+3
  meta: ^1.1.6
  geopoint: ^0.7.0
  iso: ^0.2.3
  geodesy: ^0.3.2
  rxdart: ^0.22.5

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.4.0
