name: geojson
description: Manipulate geojson data. Load and parse geojson from a string or a file.
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/geojson
version: 0.2.3

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  geopoint: ^0.4.0

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.3.0+1
  pedantic: ^1.8.0+1
