name: geojson
description: Manipulate geojson data. Load and parse geojson from a string or a file.
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/geojson
version: 0.4.0

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  geopoint: ^0.4.1
  iso: ^0.2.3
  pedantic: ^1.6.0

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.3.0+1  
