name: geojson
description: Utilities to work with geojson data. Parser with a reactive api, search and geofencing
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/geojson
version: 0.5.0

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.6
  geopoint: ^0.5.0
  iso: ^0.2.3
  pedantic: ^1.6.0
  geodesy: ^0.3.1
  rxdart: ^0.22.1+1

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.3.0+1
